services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: media-ranking-backend
    ports:
      - "127.0.0.1:34193:34193"  # Bind to localhost only, nginx will proxy
    volumes:
      - backend-data:/data
      - backend-uploads:/uploads
    environment:
      - DATABASE_URL=sqlite:/data/media_ranking.db?mode=rwc
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-in-production}
      - UPLOAD_DIR=/uploads
      - HOST=0.0.0.0
      - PORT=34193
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:7429}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-noreply@nocturnal.health}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Nocturnal Surveys}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:34193/api/admin/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - media-ranking-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:34193/api}
    container_name: media-ranking-frontend
    ports:
      - "127.0.0.1:7429:80"  # Bind to localhost only, nginx will proxy
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - media-ranking-network

volumes:
  backend-data:
    driver: local
  backend-uploads:
    driver: local

networks:
  media-ranking-network:
    driver: bridge
